apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: database # <<< ADICIONADO: Boa prática
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # 10GB é um bom começo e está dentro da cota gratuita do GKE