apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: database # <<< ADICIONADO: Namespace correto
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service" # Nome do serviço que vamos criar
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Imagem oficial do MySQL
        ports:
        - containerPort: 3306
          name: mysql

        # Variáveis que a imagem oficial do MySQL entende
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database

        # Montando o volume persistente para guardar os dados
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

        # Pedido de recursos bem menor
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

  # Seção que conecta o StatefulSet ao PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: database # <<< ADICIONADO: Namespace correto
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-service" # Nome do serviço que vamos criar
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Imagem oficial do MySQL
        ports:
        - containerPort: 3306
          name: mysql

        # Variáveis que a imagem oficial do MySQL entende
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database

        # Montando o volume persistente para guardar os dados
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

        # Pedido de recursos bem menor
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

  # Seção que conecta o StatefulSet ao PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi