<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # <<< CORRIGIDO: Aponta para a imagem que vamos subir
        image: us-central1-docker.pkg.dev/lexical-rock-462108-d8/projeto-final-imagens/lista-itens-backend:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001 # <<< CORRIGIDO: Porta da nossa aplicação Node.js
          name: http

        # <<< CORRIGIDO: Estrutura de variáveis mais limpa e correta
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: secret

        # Variáveis que o nosso código Node.js realmente espera
        env:
        - name: DB_HOST
          value: "mysql-service.database.svc.cluster.local" # Aponta para o serviço do BD
        - name: DB_USER
          value: "root" # Usuário direto
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-root-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database

        # <<< CORRIGIDO: Pedido de recursos bem menor, compatível com e2-small
        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "50m"
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # <<< CORRIGIDO: Aponta para a imagem que vamos subir
        image: us-central1-docker.pkg.dev/lexical-rock-462108-d8/projeto-final-imagens/lista-itens-backend:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3001 # <<< CORRIGIDO: Porta da nossa aplicação Node.js
          name: http

        # <<< CORRIGIDO: Estrutura de variáveis mais limpa e correta
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: secret

        # Variáveis que o nosso código Node.js realmente espera
        env:
        - name: DB_HOST
          value: "mysql-service.database.svc.cluster.local" # Aponta para o serviço do BD
        - name: DB_USER
          value: "root" # Usuário direto
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-root-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-database

        # <<< CORRIGIDO: Pedido de recursos bem menor, compatível com e2-small
        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "50m"
>>>>>>> 08f6bc72d9238c15f6ad4fe5ced10bc8e4af9392
            memory: "128Mi"