<<<<<<< HEAD
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  NODE_ENV: "production"
  PUBLIC_BASE_URL: "/"
=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  NODE_ENV: "production"
  PUBLIC_BASE_URL: "/"
>>>>>>> 08f6bc72d9238c15f6ad4fe5ced10bc8e4af9392
