name: DEBUG - Teste de Autenticação do Terraform

# Permite acionamento manual
on:
  workflow_dispatch:

jobs:
  debug-terraform-auth:
    name: 'DEBUG - Testar Autenticação do Terraform'
    runs-on: ubuntu-latest
    
    env:
      # Use as variáveis corretas para o seu ambiente de Produção
      GCP_PROJECT_ID: "festive-post-461507-v9"

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup gcloud
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 1. Autenticar e Expor Credenciais
      run: |
        echo "A tentar autenticar..."
        echo '${{ secrets.GCP_SA_KEY_PROD }}' > gcloud-key.json
        gcloud auth activate-service-account --key-file=gcloud-key.json
        gcloud config set project ${{ env.GCP_PROJECT_ID }}
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcloud-key.json" >> $GITHUB_ENV
        echo "Passo de autenticação concluído."

    - name: 2. Verificar o Contexto de Autenticação
      run: |
        echo "--- A verificar o gcloud auth list ---"
        gcloud auth list
        echo "--- A verificar a variável de ambiente GOOGLE_APPLICATION_CREDENTIALS ---"
        echo "Variável está definida como: $GOOGLE_APPLICATION_CREDENTIALS"
        echo "--- A verificar o conteúdo do ficheiro de chave (apenas o e-mail) ---"
        grep "client_email" gcloud-key.json

    - name: 3. Setup do Terraform
      uses: hashicorp/setup-terraform@v3

    - name: 4. Executar Terraform Init com LOGS DE DEPURAÇÃO
      run: |
        echo "--- A executar Terraform Init com Logging de Depuração ---"
        # TF_LOG=DEBUG força o Terraform a imprimir todos os detalhes da sua execução.
        TF_LOG=DEBUG terraform init -input=false
      working-directory: ./terraform
