name: CI/CD Pipeline for Stage Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform IaC (Infra as Code)'
    runs-on: ubuntu-latest
    
    env:
      # Substitua pelo nome do bucket que você definiu
      TF_STATE_BUCKET: "bucket-tfstate-diogo-462108"
      GCP_PROJECT_ID: lexical-rock-462108-d8 # Adicionado para uso no gcloud
      GCP_LOCATION: US-CENTRAL1 # Adicionado para uso no gcloud

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Autenticar no Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_STAGE }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # --- ETAPA A: GARANTIR QUE O BUCKET DE ESTADO EXISTA ---
    - name: Checar se o bucket de estado existe (Método Robusto)
      id: check_bucket
      run: gcloud storage buckets describe gs://${{ env.TF_STATE_BUCKET }}
      continue-on-error: true # Se o bucket não existir, o comando falha, mas a pipeline continua.

    - name: Criar bucket de estado (se não existir)
      # SÓ RODA SE O PASSO ANTERIOR FALHOU (ou seja, o bucket não existe)
      if: steps.check_bucket.outcome == 'failure'
      run: |
        echo "Bucket não encontrado. Criando bucket de estado..."
        gcloud storage buckets create gs://${{ env.TF_STATE_BUCKET }} --project=${{ env.GCP_PROJECT_ID }} --location=${{ env.GCP_LOCATION }} --uniform-bucket-level-access

    # --- ETAPA B: INFRAESTRUTURA PRINCIPAL ---
    - name: Terraform Init (Conecta ao bucket)
      run: terraform init -input=false
      working-directory: ./terraform
      
    - name: Terraform Apply (Cria/Atualiza o cluster)
      run: terraform apply -auto-approve
      working-directory: ./terraform

  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Instalar dependências do Backend
        working-directory: ./backend
        run: npm install
      - name: Rodar testes do Backend
        working-directory: ./backend
        run: npm test

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test # <<< SÓ RODA DEPOIS QUE OS TESTES PASSAREM
    env:
      GCP_PROJECT_ID: lexical-rock-462108-d8
      GCP_REGION: us-central1
      ARTIFACT_REPO: projeto-final-imagens
      IMAGE_BACKEND: lista-itens-backend
      IMAGE_FRONTEND: lista-itens-frontend
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGE }}
      - name: Configurar Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev
      - name: Build e Push do Backend
        run: |
          docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }} ./backend
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_BACKEND }}:${{ github.sha }}
      - name: Build e Push do Frontend
        run: |
          docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_FRONTEND }}:${{ github.sha }} ./frontend
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_FRONTEND }}:${{ github.sha }}

  deploy:
    name: Deploy to GKE Stage
    runs-on: ubuntu-latest
    needs: build-and-push # <<< SÓ RODA DEPOIS DO BUILD E PUSH
    env:
      GCP_PROJECT_ID: lexical-rock-462108-d8
      GKE_CLUSTER: cluster-1
      GKE_ZONE: us-central1-a
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup gcloud CLI with GKE Auth Plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          # Garante a instalação do plugin e kubectl
          install_components: 'gke-gcloud-auth-plugin,kubectl'
          # Exporta automaticamente para o PATH

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGE }}
      - name: Conectar ao cluster GKE
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
      - name: Substituir a Tag da Imagem nos Deployments
        run: |
          sed -i 's|lista-itens-backend:.*|lista-itens-backend:${{ github.sha }}|g' ./arquivos/backend-config/backend-deployment.yaml
          sed -i 's|lista-itens-frontend:.*|lista-itens-frontend:${{ github.sha }}|g' ./arquivos/frontend-config/frontend-deployment.yaml
      - name: Deploy no Kubernetes
        run: |
          echo "INFO: Aplicando namespaces primeiro..."
          find ./arquivos -name "namespaces.yaml" -exec kubectl apply -f {} \;
          
          echo "INFO: Aguardando 5 segundos para a propagação dos namespaces..."
          sleep 5
          
          echo "INFO: Aplicando os outros recursos..."
          kubectl apply -R -f ./arquivos/